feature: バージョン管理機能を持ったファイルシステム
sai-lab/sai-lab.github.io pull request #39
Opened 2022-06-17 14:22 UTC by higuruchi

2022-06-17 14:33 UTC, i13302 requested changes

2022-06-17 14:33 UTC, i13302 commented on mdfiles/wiki/theme.md
> +[試行錯誤しながら自学自習できる体験型セキュリティ演習システム](#試行錯誤しながら自学自習できる体験型セキュリティ演習システム)
なぜ書き換え？

2022-06-17 14:33 UTC, i13302 commented on mdfiles/wiki/theme.md
> +このような，学生をサポートし，底上げするシステムを開発することで，セキュリティ人材の育成に寄与します．
なぜ書き換え

2022-06-17 14:33 UTC, i13302 commented on mdfiles/wiki/theme.md
> +
図を1枚ぐらい欲しい．

2022-06-17 14:33 UTC, i13302 commented on mdfiles/wiki/theme.md
> +近年、ランサムウェアによる被害の件数は増加しています。ランサムウェアに感染した場合、ファイルのデータが暗号化され、業務の継続が困難になり多額の損害が生じます。また、企業イメージの低下などの2次被害も甚大です。しかし、Linuxなどで用いられるファイルシステムにはバージョン管理機能がなく、ファイルのデータを暗号化や削除された場合、データを復元することは困難です。
> しかし、Linuxなどで用いられるファイルシステムにはバージョン管理機能がなく、ファイルのデータを暗号化や削除された場合、データを復元することは困難です。

ファイルのデータがさくじょされた～～～～ → バージョン管理機能で解決できそう
という流れで．

2022-06-17 14:33 UTC, i13302 commented on mdfiles/wiki/theme.md
> +本研究では、ファイルに対する書き込みを自動でバージョン管理することによって、ランサムウェアによる攻撃被害にあったとしても、即座にデータの復元ができることを目的としています。
改行，句読点をあわせて．

2022-06-17 14:33 UTC, i13302 commented on mdfiles/wiki/theme.md
> +もちろん適切にデータのバックアップを行っていれば、ほとんどのデータを取り戻すことは可能ですが、バックアップが完了してから攻撃されるまでに生じたファイルの変更が消失してしまいます。
> もちろん

不要

2022-06-17 14:33 UTC, i13302 commented on mdfiles/wiki/theme.md
> +もちろん適切にデータのバックアップを行っていれば、ほとんどのデータを取り戻すことは可能ですが、バックアップが完了してから攻撃されるまでに生じたファイルの変更が消失してしまいます。
> バックアップが完了してから攻撃されるまでに生じたファイルの変更

図があると良い．

2022-06-17 14:37 UTC, kakukaku-15 commented on mdfiles/wiki/theme.md
> +[試行錯誤しながら自学自習できる体験型セキュリティ演習システム](#試行錯誤しながら自学自習できる体験型セキュリティ演習システム)
末尾の空白抜けたとか

2022-06-20 07:31 UTC, i13302 commented on mdfiles/wiki/theme.md
> +近年，ランサムウェアによる被害の件数は増加しています。
1文枚の文末に空行は必要？ @kakukaku-15

2022-06-20 07:32 UTC, i13302 commented on mdfiles/wiki/theme.md
> +近年，ランサムウェアによる被害の件数は増加しています。
あと，。を．に．

2022-06-20 07:37 UTC, i13302 requested changes

2022-06-20 07:37 UTC, i13302 commented on mdfiles/wiki/theme.md
> +ランサムウェアに感染した場合，ファイルのデータが暗号化され，業務の継続が困難になり多額の損害が生じます. また，企業イメージの低下などの2次被害も甚大です．
> また，企業イメージの低下などの2次被害も甚大です．

いる？

2022-06-20 07:37 UTC, i13302 commented on mdfiles/wiki/theme.md
> +しかし，Linuxなどで用いられるファイルシステムにはバージョン管理機能がなく，ファイルのデータを暗号化や削除された場合，データを復元することは困難です．
> ファイルシステムにはバージョン管理機能がなく

バージョン管理機能の話がでるのが早い．
まずは背景，課題を書いて，解決方法としてバージョン管理機能を提示する流れに．

2022-06-20 07:37 UTC, i13302 commented on mdfiles/wiki/theme.md
> +適切にデータのバックアップを行っていれば，ほとんどのデータを取り戻すことは可能ですが，バックアップが完了してから攻撃されるまでに生じたファイルの変更が消失してしまいます．
> データのバックアップ

文頭でのランサムウェアとの関係は？

2022-06-20 07:37 UTC, i13302 commented on mdfiles/wiki/theme.md
> +本研究では，ファイルに対する書き込みを自動でバージョン管理することによって，ランサムウェアによる攻撃被害にあったとしても，即座にデータの復元ができることを目的としています．
> 攻撃被害にあった

日本語がおかしい．

2022-06-20 07:37 UTC, i13302 commented on mdfiles/wiki/theme.md
> +本研究では，ファイルに対する書き込みを自動でバージョン管理することによって，ランサムウェアによる攻撃被害にあったとしても，即座にデータの復元ができることを目的としています．
> 即座にデータの復元

バックアップを取ったときとの違いは？

2022-06-20 07:37 UTC, i13302 commented on mdfiles/wiki/theme.md
> +<img src="../images/theme/yuiha-fs-backup.png" alt="protec-kun_01" width="50%">
図がよくわからない．

- 矢印の意味は
- バックアップサーバとは？文章中にもない．
- バックアップを取る対象は？
- 右半分の分岐の意味は？
- ファイルのアイコンがコロコロ変わる意味は？

2022-06-20 13:59 UTC, higuruchi commented
水曜までに修正完了させます

2022-06-20 14:11 UTC, kakukaku-15 commented on mdfiles/wiki/theme.md
> +近年，ランサムウェアによる被害の件数は増加しています。
> 1文枚の文末に空行は必要？ @kakukaku-15

そのへんはお好みで

2022-06-23 01:41 UTC, i13302 requested changes

2022-06-23 01:41 UTC, i13302 commented on mdfiles/wiki/theme.md
> +<img src="../images/theme/yuiha-fs-backup.png" alt="yuiha-fs" width="100%">
- バージョンは，リターンなのかリストアなのか．
- ファイルの色づかいが悪い．マルウェアが赤色なので，オレンジ色のファイルは異常なファイル，青色のファイルは正常なファイルに見える
- 目が意味不明．`ls` コマンドの実行結果とか貼っ付けるのもありかもしれない．

2022-06-23 01:41 UTC, i13302 commented on mdfiles/wiki/theme.md
> +通常は, バックアップを取りデータの消失に対応するのですが, バックアップのコストは高く，1日に1回です.
文法と `，．` の使い方がおかしい．
主語はどれ？

2022-06-23 01:41 UTC, i13302 commented on mdfiles/wiki/theme.md
> +そのため，バックアップをとってから攻撃されるまでに生じたファイルの変更が消失してしまいます.
攻撃という用語は上記でどこにも出ていない．
```
バックアップを取ってから編集したファイルが，ランサムウェアによって暗号化された場合，そのファイルの編集内容を復元させることは難しいです．
```
とか？

2022-06-23 01:41 UTC, i13302 commented on mdfiles/wiki/theme.md
> +本研究では，ファイル操作単位でバージョン管理を行い, 攻撃される直前のファイルの状態に復元することを目的としています.
> ファイル操作単位

ファイル操作という単位はない．
`ファイル操作毎(open，...)` とか．

Gitとの違いがわからない．
技術用語(ファイルシステムとか)を入れる．

マルウェアによる云々は，このバージョン管理を使ったときの応用事例なので，バージョン管理だけで何ができるのかを示す．

2022-06-23 01:41 UTC, i13302 commented on mdfiles/wiki/theme.md
> +## バージョン管理機能を持ったファイルシステム　
> 持った

持つ

2022-06-23 01:41 UTC, i13302 commented on mdfiles/wiki/theme.md
> +[バージョン管理機能を持ったファイルシステム](#バージョン管理機能を持ったファイルシステム)
> 持った

持つ

2022-06-23 01:42 UTC, i13302 commented
昨日も言ったけどlabelは，マージ待ちなのか，作業待ちなのか

2022-06-23 05:07 UTC, higuruchi commented
> **昨日も言ったけど**labelは，マージ待ちなのか，作業待ちなのか

外し忘れてました。すみません

2022-06-27 05:53 UTC, i13302 requested changes

2022-06-27 05:53 UTC, i13302 commented on mdfiles/wiki/theme.md
> +<img src="../images/theme/yuiha-fs-backup.png" alt="yuiha-fs" width="100%">
- `ls` 消して `cat` だけに．
- 黒画面やめてほしい

2022-06-27 05:53 UTC, i13302 commented on mdfiles/wiki/theme.md
> +本研究では，ファイル操作毎(open，...)に自動でバージョン作成を行い, 過去のファイルの状態に戻れるファイルシステムの開発をしています.
> 本研究では，フ
半角になってる

> ファイル操作毎(open，...)
open以外は？三点リーダー書くなら，2つぐらい例示して．
日本語でかけない？

> ァイルシステムの開発をしています.
ファイルシステムを開発しています．

2022-07-06 00:12 UTC, kakukaku-15 approved these changes

2022-07-06 00:15 UTC, i13302 approved these changes

2022-07-06 00:16 UTC, merged