Add 2022
sai-lab/sai-lab.github.io pull request #66
Opened 2023-03-30 09:42 UTC by knit0117

2022年の内容を追加しました．

github actionsでリンクエラーが出るところは現在のホームページだと正常に動作しているようなのでそのままにしてあります．

2023-03-30 09:54 UTC, i13302 requested changes
- CIが落ちている理由を調査してほしいです．CIのビルド結果ではPDFが表示されていません．過去の記録を見ると落ちていません．
- 追いコンについて雑すぎます．
  - 場所，メンバー，日時，イベント(プレゼント渡し)などを入れてください．
- 勉強会について雑すぎます．最所研に入りたい学生(B3)の全員が意味もわからないPDF見なきゃいけないの？
忙しくて無理そうでしたら言ってください．

2023-03-30 11:14 UTC, i13302 commented
あとはブランチ名が悪い

2023-03-31 09:16 UTC, knit0117 commented
> CIが落ちている理由を調査してほしいです．CIのビルド結果ではPDFが表示されていません．過去の記録を見ると落ちていません．
確認します．分からない場合は石塚さんなどに聞いてみます．

> 追いコンについて雑すぎます．  
> 場所，メンバー，日時，イベント(プレゼント渡し)などを入れてください．
それらの項目をいれた詳しい内容に修正します．

> 勉強会について雑すぎます．最所研に入りたい学生(B3)の全員が意味もわからないPDF見なきゃいけないの？
各項目について説明を追加します．

> あとはプルリク名が悪い
変更内容が分かるよう，以後気を付けます．

2023-03-31 09:54 UTC, i13302 commented
> それらの項目をいれた詳しい内容に修正します．
>> 勉強会について雑すぎます．最所研に入りたい学生(B3)の全員が意味もわからないPDF見なきゃいけないの？
PDFの中身を数枚pngで貼り付けて，なんのために，どのように，何を勉強しているか分かるように．
研究テーマのページを参考に．

2023-04-06 06:21 UTC, knit0117 commented
CIが落ちている理由は，リンクが切れている箇所はmdfile/static/index.htmlを参照しようとしているがそのディレクトリにはindex.mdしか存在せず，mdファイルがhtmlファイルに変換されていないのが原因だと考えられます．

解決方法は調査中です．

2023-04-11 05:29 UTC, tomoaki0513 commented
`mdfiles/wili/theme.md`のpdfのリンクの貼り方を修正
`../static/index.html?FILE=../public_material/poster-2022_CyberEducation.pdf`
↓
`../public_material/poster-2022_CyberEducation.pdf`
衣川くんこれで大丈夫かチェックお願い

2023-04-11 05:36 UTC, knit0117 commented
> `mdfiles/wili/theme.md`のpdfのリンクの貼り方を修正 `../static/index.html?FILE=../public_material/poster-2022_CyberEducation.pdf` ↓ `../public_material/poster-2022_CyberEducation.pdf` 衣川くんこれで大丈夫かチェックお願い

その方法だと以前の資料公開一覧ページに飛ばす方式からPDFファイルが開く方式に変わると思いますが大丈夫ですかね？
大きな差ではないとは思いますが

2023-04-11 05:48 UTC, tomoaki0513 commented
> > `mdfiles/wili/theme.md`のpdfのリンクの貼り方を修正 `../static/index.html?FILE=../public_material/poster-2022_CyberEducation.pdf` ↓ `../public_material/poster-2022_CyberEducation.pdf` 衣川くんこれで大丈夫かチェックお願い
> 
> その方法だと以前の資料公開一覧ページに飛ばす方式からPDFファイルが開く方式に変わると思いますが大丈夫ですかね？ 大きな差ではないとは思いますが

なんかBEYONDの方だとそのままPDF開いてたからそれに合わせんたんやけど本来はページ遷移する方式か
一旦保留で

2023-05-15 08:38 UTC, knit0117 commented
@i13302 
ホームページ編集したのでチェックをお願いします．

2023-05-17 05:40 UTC, i13302 commented
何この地獄みたいなコミットメッセージ．

2023-05-17 05:56 UTC, i13302 commented
@knit0117 
- 研究テーマは更新しました？

2023-05-23 16:12 UTC, i13302 approved these changes

2023-05-23 16:12 UTC, merged