Fix/update 2024
sai-lab/sai-lab.github.io pull request #79
Opened 2024-04-03 07:49 UTC by higuruchi

- 追いコンの画像，参加者を2023年度版に更新
- 2023年度の論文実績を追加
- 研究室所属メンバーを更新

2024-04-04 02:52 UTC, i13302 requested changes

2024-04-04 02:52 UTC, i13302 commented on mdfiles/wiki/assign.md
> +お世話になった先生方に今までのお礼や，感謝を込めてプレゼントを差し上げました．
差し上げたって，敬語がおかしいような．

2024-04-04 02:52 UTC, i13302 commented on mdfiles/wiki/member.md
>  ### 工学研究科 博士後期課程(博士)2年
3年

2024-04-04 02:52 UTC, i13302 commented on mdfiles/wiki/member.md
>  [工学研究科 博士後期課程(博士)2年](#工学研究科-博士後期課程博士2年)
3年

2024-04-04 05:43 UTC, i13302 requested changes

2024-04-04 05:43 UTC, i13302 commented on mdfiles/wiki/member.md
>  [創発科学研究科 博士前期課程(修士)1年](#創発科学研究科-博士前期課程修士1年)
修士2年

2024-04-04 09:54 UTC, higuruchi commented on mdfiles/wiki/assign.md
> +お世話になった先生方に今までのお礼や，感謝を込めてプレゼントを差し上げました．
「贈りました」とかですかね

2024-04-04 17:36 UTC, i13302 requested changes
> ### 工学研究科 博士後期課程(博士)2年

3年。

2024-04-04 17:36 UTC, i13302 commented on mdfiles/wiki/member.md
> +[創発科学研究科 博士前期課程(修士)2年](#創発科学研究科-博士前期課程修士1年)
```suggestion
[工学研究科 博士後期課程(博士)3年](#工学研究科-博士後期課程博士3年)
[創発科学研究科 博士前期課程(修士)2年](#創発科学研究科-博士前期課程修士2年)  
```

2024-04-09 07:08 UTC, i13302 commented
@higuruchi いつできる？

2024-04-09 14:36 UTC, i13302 approved these changes

2024-04-09 14:37 UTC, merged